#!/usr/bin/env bash
# setup.sh — One-time personalization for hgryoo/dotfiles
# Run once after install.sh and auth.sh.
# Safe to re-run — all steps are idempotent.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_FILE="$SCRIPT_DIR/secrets.env"
ENV_FILE="$HOME/.config/personal/env"

# ---------------------------------------------------------------------------
# Load secrets (optional — skip if not yet created)
# ---------------------------------------------------------------------------
load_secrets() {
  if [ -f "$SECRETS_FILE" ]; then
    set -a; source "$SECRETS_FILE"; set +a
    echo ">>> Loaded secrets from $SECRETS_FILE"
  else
    echo "WARNING: $SECRETS_FILE not found — API key env vars will not be set."
    echo "  Run: cp secrets.env.template secrets.env && \$EDITOR secrets.env"
  fi
}

# ---------------------------------------------------------------------------
# git config
# ---------------------------------------------------------------------------
setup_git() {
  echo
  echo "--- git config ---"
  local current_name current_email current_editor
  current_name=$(git config --global user.name 2>/dev/null || true)
  current_email=$(git config --global user.email 2>/dev/null || true)
  current_editor=$(git config --global core.editor 2>/dev/null || true)

  read -r -p "git user.name  [${current_name:-not set}]: " name
  name="${name:-$current_name}"
  [ -n "$name" ] && git config --global user.name "$name"

  read -r -p "git user.email [${current_email:-not set}]: " email
  email="${email:-$current_email}"
  [ -n "$email" ] && git config --global user.email "$email"

  read -r -p "git core.editor [${current_editor:-vim}]: " editor
  editor="${editor:-${current_editor:-vim}}"
  git config --global core.editor "$editor"

  git config --global init.defaultBranch main
  git config --global pull.rebase false

  echo ">>> git config done: name='$name' email='$email' editor='$editor'"
}

# ---------------------------------------------------------------------------
# Persist env vars to ~/.config/personal/env
# Sourced once from ~/.bashrc
# ---------------------------------------------------------------------------
setup_env() {
  echo
  echo "--- Persisting env vars ---"
  mkdir -p "$(dirname "$ENV_FILE")"

  cat > "$ENV_FILE" <<EOF
# Personal env — generated by setup.sh. Do not commit.
# Re-run setup.sh to regenerate.

$([ -n "${ANTHROPIC_API_KEY:-}" ]   && echo "export ANTHROPIC_API_KEY='${ANTHROPIC_API_KEY}'"   || echo "# ANTHROPIC_API_KEY not set")
$([ -n "${GITHUB_TOKEN:-}" ]        && echo "export GITHUB_TOKEN='${GITHUB_TOKEN}'"              || echo "# GITHUB_TOKEN not set")
$([ -n "${HUGGINGFACE_TOKEN:-}" ]   && echo "export HUGGINGFACE_TOKEN='${HUGGINGFACE_TOKEN}'"    || echo "# HUGGINGFACE_TOKEN not set")
$([ -n "${JIRA_URL:-}" ]            && echo "export JIRA_URL='${JIRA_URL}'"                      || echo "# JIRA_URL not set")
$([ -n "${JIRA_USERNAME:-}" ]       && echo "export JIRA_USERNAME='${JIRA_USERNAME}'"            || echo "# JIRA_USERNAME not set")
$([ -n "${JIRA_API_TOKEN:-}" ]      && echo "export JIRA_API_TOKEN='${JIRA_API_TOKEN}'"          || echo "# JIRA_API_TOKEN not set")
$([ -n "${RTK_API_KEY:-}" ]         && echo "export RTK_API_KEY='${RTK_API_KEY}'"                || echo "# RTK_API_KEY not set")
$([ -n "${GOOGLE_CLIENT_ID:-}" ]    && echo "export GOOGLE_CLIENT_ID='${GOOGLE_CLIENT_ID}'"      || echo "# GOOGLE_CLIENT_ID not set")
$([ -n "${GOOGLE_CLIENT_SECRET:-}" ] && echo "export GOOGLE_CLIENT_SECRET='${GOOGLE_CLIENT_SECRET}'" || echo "# GOOGLE_CLIENT_SECRET not set")
EOF

  # Add source line to ~/.bashrc if not already present
  local source_line="[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\""
  if ! grep -qF "$ENV_FILE" "$HOME/.bashrc" 2>/dev/null; then
    echo "" >> "$HOME/.bashrc"
    echo "# Personal env (generated by dotfiles setup.sh)" >> "$HOME/.bashrc"
    echo "$source_line" >> "$HOME/.bashrc"
    echo ">>> Added source line to ~/.bashrc"
  else
    echo ">>> ~/.bashrc already sources $ENV_FILE"
  fi

  echo ">>> Env vars written to $ENV_FILE"
}

# ---------------------------------------------------------------------------
# Full environment verification summary
# ---------------------------------------------------------------------------
print_summary() {
  echo
  echo "============================================================"
  echo " Environment summary"
  echo "============================================================"

  echo "--- Base ---"
  command -v gcc    &>/dev/null && echo "GCC        : $(gcc --version | head -n1)"   || echo "GCC        : not found"
  command -v cmake  &>/dev/null && echo "CMake      : $(cmake --version | head -n1)" || echo "CMake      : not found"
  command -v ninja  &>/dev/null && echo "Ninja      : $(ninja --version)"             || echo "Ninja      : not found"
  command -v java   &>/dev/null && echo "Java       : $(java -version 2>&1 | head -n1)" || echo "Java       : not found"

  echo "--- Languages / Runtimes ---"
  command -v uv     &>/dev/null && echo "uv         : $(uv --version)"                || echo "uv         : not found"
  command -v rustc  &>/dev/null && echo "Rust       : $(rustc --version)"             || echo "Rust       : not found"
  command -v node   &>/dev/null && echo "Node.js    : $(node --version)"              || echo "Node.js    : not found"
  command -v npm    &>/dev/null && echo "npm        : $(npm --version)"               || echo "npm        : not found"

  echo "--- Shell / Editor ---"
  command -v nvim   &>/dev/null && echo "Neovim     : $(nvim --version | head -n1)"  || echo "Neovim     : not found"
  command -v direnv &>/dev/null && echo "direnv     : $(direnv --version)"            || echo "direnv     : not found"
  command -v fzf    &>/dev/null && echo "fzf        : $(fzf --version)"               || echo "fzf        : not found"
  command -v just   &>/dev/null && echo "just       : $(just --version)"              || echo "just       : not found"

  echo "--- CLI Tools ---"
  command -v gh        &>/dev/null && echo "gh         : $(gh --version | head -n1)"   || echo "gh         : not found"
  command -v rtk       &>/dev/null && echo "rtk        : $(rtk --version 2>/dev/null | head -n1)" || echo "rtk        : not found"
  command -v markitdown &>/dev/null && echo "markitdown : installed"                   || echo "markitdown : not found"
  command -v lazydiff  &>/dev/null && echo "lazydiff   : installed"                    || echo "lazydiff   : not found"
  command -v lazygit   &>/dev/null && echo "lazygit    : $(lazygit --version | head -n1)" || echo "lazygit    : not found"

  echo "--- AI / Claude ---"
  command -v claude &>/dev/null && echo "claude     : $(claude --version | head -n1)" || echo "claude     : not found"
  command -v omc    &>/dev/null && echo "omc        : installed"                       || echo "omc        : not found"

  echo "--- Local LLM ---"
  command -v ollama    &>/dev/null && echo "ollama     : $(ollama --version 2>/dev/null | head -n1)" || echo "ollama     : not found"
  [ -x "$HOME/.local/share/llama.cpp/build/bin/llama-cli" ] && echo "llama.cpp  : built" || echo "llama.cpp  : not found"
  [ -x "$HOME/.local/share/vllm-env/bin/vllm" ] && echo "vLLM       : installed"      || echo "vLLM       : not found"
  command -v ollama &>/dev/null && ollama list 2>/dev/null | grep -q "gemma4" && echo "gemma4     : pulled" || echo "gemma4     : not pulled"

  echo "--- CUBRID Tools ---"
  [ -f "$HOME/dotfiles/cubrid/tools/cubrid-jira-fetcher/fetcher.py" ] && echo "cubrid-jira-fetcher: present" || echo "cubrid-jira-fetcher: not found"
  command -v pandoc &>/dev/null && echo "pandoc     : $(pandoc --version | head -n1)" || echo "pandoc     : not found"

  echo "--- Knowledge Base ---"
  command -v obsidian &>/dev/null && echo "obsidian-cli: $(obsidian --version 2>/dev/null | head -n1)" || echo "obsidian-cli: not found"
  command -v qmd      &>/dev/null && echo "qmd        : installed"                     || echo "qmd        : not found"
  command -v gws      &>/dev/null && echo "gws        : installed"                     || echo "gws        : not found"
  [ -d "$HOME/obsidian" ]  && echo "~/obsidian : exists"  || echo "~/obsidian : not created"
  [ -d "$HOME/knowledge" ] && echo "~/knowledge: exists"  || echo "~/knowledge: not created"

  echo "--- Env Vars ---"
  [ -n "${ANTHROPIC_API_KEY:-}" ]  && echo "ANTHROPIC_API_KEY  : set" || echo "ANTHROPIC_API_KEY  : not set"
  [ -n "${GITHUB_TOKEN:-}" ]       && echo "GITHUB_TOKEN       : set" || echo "GITHUB_TOKEN       : not set"
  [ -n "${HUGGINGFACE_TOKEN:-}" ]  && echo "HUGGINGFACE_TOKEN  : set" || echo "HUGGINGFACE_TOKEN  : not set"
  [ -n "${JIRA_API_TOKEN:-}" ]     && echo "JIRA_API_TOKEN     : set" || echo "JIRA_API_TOKEN     : not set"
  [ -n "${RTK_API_KEY:-}" ]        && echo "RTK_API_KEY        : set" || echo "RTK_API_KEY        : not set"
  [ -n "${GOOGLE_CLIENT_ID:-}" ]   && echo "GOOGLE_CLIENT_ID   : set" || echo "GOOGLE_CLIENT_ID   : not set"

  echo "============================================================"
  echo "Done! Run 'source ~/.bashrc' to reload your shell."
  echo "============================================================"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  load_secrets
  setup_git
  setup_env
  print_summary
}

main "$@"
